name: coverage-badge

# This workflow will
# run all tests with pytest  
on: [push]

jobs:
 
  tests:
   runs-on: ubuntu-18.04
   strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.9]
   steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}    
    - name: Test python version ${{ matrix.python-version }} and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r devel-requirements.txt
    - name: Run Tests and create coverage badge
      run: |
        pytest -v 
        coverage-badge -f  -o coverage.svg
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add coverage.svg
        git commit -m "Update coverage badge" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
