name: Pages
# This workflow will
# Autobuild manpage on every  merge and make it available on GitHub pages
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: docs

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
