name: pytest

# This workflow will
# run all tests with pytest  
on: [push, pull_request]

jobs:
  
  tests:
   runs-on: ubuntu-18.04
   strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8, 3.9]
   steps:
     
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}    

    - name: Test python version [2.7, 3.6, 3.7, 3.8, 3.9] and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov mock

    - name: Test with pytest
      run: pytest -v



      